# Generated by Django 6.0 on 2026-01-03 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Frontmatter-like arbitrary metadata",
                    ),
                ),
                (
                    "doctype",
                    models.CharField(
                        choices=[
                            ("study", "Study"),
                            ("journal", "Journal"),
                            ("project", "Project"),
                            ("task", "Task"),
                            ("temp", "Temp"),
                            ("other", "Other"),
                        ],
                        default="temp",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Semantic date (mainly for journal entries)",
                        null=True,
                    ),
                ),
                (
                    "interval",
                    models.JSONField(
                        blank=True,
                        help_text="Semantic time interval (mainly for journal entries)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["doctype"], name="notes_note_doctype_e2d1bd_idx"
                    ),
                    models.Index(fields=["date"], name="notes_note_date_b8e64e_idx"),
                ],
            },
        ),
    ]
